# Site
name: "ಜ್ಞಾನ ಸಂಗಮ"
title: "ಜ್ಞಾನ ಸಂಗಮ"
description: "ನಮ್ಮ ಜ್ಞಾನ ಸಂಗಮವು ಪವಿತ್ರ ತ್ರಿವೇಣೀಸಂಗಮದಂತೆ ಮೂಡುವ ದೃಷ್ಟಿ ಹೊಂದಿದೆ, ನಮ್ಮ ಪ್ರಯತ್ನವೂ ರಾಷ್ಟ್ರೀಯ ವಿಚಾರಗಳು, ಸಾಂಸ್ಕೃತಿಕ ಜಾಗೃತಿ ಮತ್ತು ಅತ್ಯುನ್ನತ ತಂತ್ರಜ್ಞಾನದ ಸಂಗಮವಾಗಿದೆ. ಇವೆಲ್ಲದರ ಜೊತೆಗೆ ಉತ್ತಮ ವಾಗ್ಮಿ ಮತ್ತು ಲೇಖಕರಿಂದ ವಿಚಾರ ವಿಮರ್ಶೆಗಳು ಮತ್ತು ಯುವ ಪ್ರತಿಭೆಗಳಿಗೆ ಉತ್ತೇಜನೆ ನೀಡುವ ವೇದಿಕೆಯಾಗಲಿದೆ."
logo: 'assets/images/brand/logo.png'
favicon: 'assets/images/brand/favicon.png'
baseurl: /blog
google_analytics: 'G-8MWRMYHFYJ'
disqus: 'blog-gnanasangama'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  akshaygj:
    name: ಅಕ್ಷಯ್ ಜೋಗಿಹಳ್ಳಿ
    display_name: ಅಕ್ಷಯ್ ಜೋಗಿಹಳ್ಳಿ
    gravatar: 
    email: akshaygj.abhyudaya@gmail.com
    web: /blog/author/akshaygj
    twitter: https://twitter.com/akshaygj
    description: "ಲೇಖಕ"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
